### ISSUE TITLE
Is there a workaround for "Version mismatch between HSA runtime and libhsa-runtime-tools64.so.1"?"

### ISSUE THREAD

**Issue by ex-rzr** [GPUOpen-Tools/RCP#17]
It's a known issue on ROCm 1.9:
https://github.com/RadeonOpenCompute/ROCm#radeon-compute-profiler-does-not-run
but perhaps you have a way to run the profiler on 1.9?

**Comment by chesik-amd** [comment]
Unfortuanetly, there isn't a workaround for this.

The good news is the the next update to ROCm 1.9 will contain a fix for this.  In the meantime, I can give you a new version of libhsa-runtime-tools64.so.1.1.9 that contains the fix.  If you replace the version of this file in /opt/rocm/hsa/lib with the new version, this issue shoud go away.

Since this is not an official delivery channel, standard caveats apply: this build hasn't yet gone through a normal QA testing cycle, so it may or may not work as expected and it may or may not cause previously-unseen issues.  Be sure to back up the existing version and use the new version at your own risk :-). If you decide to try it out, please report back with your experience.

Thanks,
Chris
[libhsa-runtime-tools64.zip](https://github.com/GPUOpen-Tools/RCP/files/2424263/libhsa-runtime-tools64.zip)

**Comment by ex-rzr** [comment]
Thank you, Chris!

I've checked API tracing only (`-A`) and it works ok so far. I let you know/open an issue if I notice something.

I think we should keep this issue open till the update to ROCm 1.9 released so other people can find how to run the profiler on the current release.

**Comment by chesik-amd** [comment]
This should no longer be an issue when using ROCM 2.0 and RCP 5.6 (actually an earlier update to ROCm 1.9 fixed this, but I forgot to come back here and update this thread)
